# Server Configuration
server.port=8080
#server.servlet.context-path=/endpoint-copy

# Application Configuration
spring.application.name=endpoint-copy

# Logging Configuration
logging.level.com.app.endpointcopy=DEBUG
logging.level.org.springframework.web=INFO
